### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by lx1054331851** [GoogleChromeLabs/squoosh#1125]
```shell
D:\squoosh-dev>npm run build

> squoosh@2.0.0 build
> rollup -c && node lib/move-output.js


src/static-build/index.tsx → .tmp/build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
[!] (plugin css) Error: Could not load css:/squoosh-dev/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \squoosh-dev\src\shared\prerendered-app\colors.css in pathToResult
Error: Could not load css:/squoosh-dev/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \squoosh-dev\src\shared\prerendered-app\colors.css in pathToResult
    at Object.load (D:\squoosh-dev\rollup.config.js:552:17)
    at D:\squoosh-dev\node_modules\rollup\dist\shared\rollup.js:18971:25
```

```shell
D:\squoosh-dev>node -v
v16.7.0

D:\squoosh-dev>npm -v
7.20.3
```

**Comment by jakearchibald** [comment]
Can you build with node 14.15.1? (that's the version in our nvmrc)

**Comment by jakearchibald** [comment]
Closing. Happy to reopen if more details are given.
