### ISSUE TITLE
"caniuse-lite is outdated" during "npm run build"

### ISSUE THREAD

**Issue by G-bug** [GoogleChromeLabs/squoosh#583]
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
SyntaxError: Invalid regular expression: /\codecs\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at module.exports (D:\NodeJs\node_global\node_modules\squoosh\webpack.config.js:175:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by heddn** [comment]
Still occurs even today.

**Comment by surma** [comment]
Pretty sure @RReverser has been building on Windows successfully for a while now. So if you are seeing this issue, something else is going on and we need more data than what OP provided.

**Comment by RReverser** [comment]
@surma Not only me - we have Windows on CI: https://github.com/GoogleChromeLabs/squoosh/runs/1880175212
