### ISSUE TITLE
[JPEX XL] Processing error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by BuyMyMojo** [GoogleChromeLabs/squoosh#869]
**Describe the bug**
The following error happens whenever I try to convert a PNG to JPEG XL for both lossless and default settings
`Processing error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.`
and in chromes console:
`Compress-e7cd1676.js:3935 Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at K (http://192.168.128.165:5000/c/jxl_enc_mt-c53402a2.js:20:221)
    at b (http://192.168.128.165:5000/c/jxl_enc_mt-c53402a2.js:83:423)
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[51]:0x1803
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[301]:0x3c35c
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[607]:0x804e5
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[1049]:0xed661
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[1059]:0xfa243
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[313]:0x469d5
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[1031]:0xe0f18
    at http://192.168.128.165:5000/c/jxl_enc_mt-cb9016c9.wasm:wasm-function[1071]:0xfeb19`

**To Reproduce**
1. Grab the images bellow
2. Try converting to JPEG XL
3. Error occurs

**Version:**
 - OS w/ version: Windows 10 (hosted from there too)
 - Browser w/ version: Chrome 87.0.4280.66 (Official Build) beta (64-bit)
 - Node version: v14.15.1
 - npm version: 6.14.8

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
[https://drive.google.com/drive/folders/1ogxL8DzdqNrSFZwC9DunzLkcvSxwGKFv?usp=sharing](https://drive.google.com/drive/folders/1ogxL8DzdqNrSFZwC9DunzLkcvSxwGKFv?usp=sharing)

**Comment by BuyMyMojo** [comment]
After rebulding with `-s ASSERTIONS=1` it worked.. I think it might just have been a build error?

**Comment by BuyMyMojo** [comment]
it works with some settings like effort 3 but when effort is 6 it fails for example

**Comment by surma** [comment]
The JXL encoder is still under development (which is why it’s marked as “unstable”). Some of the effort settings currently crash.

**Comment by BuyMyMojo** [comment]
As long as it's known 👍👍👍

**Comment by ghost** [comment]
On pixel4a / brave browser

![Screenshot_20201210-092839](https://user-images.githubusercontent.com/1514731/101785548-e681c080-3aca-11eb-9347-622258241b28.png)

**Comment by BuyMyMojo** [comment]
I just went through all levels of effort for lossless Jpeg XL with one of the same example image and it worked so fixed for lossless but had a couple errors so half way there I guess

**Comment by RReverser** [comment]
This is most likely OOM issue and something that needs to be fixed in JPEG XL itself. They already brought memory usage down significantly, but likely there's more work to be done to fit into mobile device memory constraints.
