### ISSUE TITLE
[CLI] Unhandled error when specifying an input file that doesn't exist

### ISSUE THREAD

**Issue by fernap3** [GoogleChromeLabs/squoosh#893]
**Describe the bug**
If I call `squoosh-cli` specifying an input file that doesn't exist, I get an unhandled error.  This is not a huge deal but a small UX issue I think.

**To Reproduce**

Run `squoosh-cli` with an input file that doesn't exist:

```
squoosh-cli --output-dir png --oxipng {} great-moves-keep-it-up.svg
```

**Expected behavior**
I expect the CLI to return a nonzero error code and print a nice console message telling the user that their input file doesn't exist.

**Actual behavior**
Node runtime error:

```
[Error: ENOENT: no such file or directory, open '[FILEPATH]\great-moves-keep-it-up.svg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '[FILEPATH]\great-moves-keep-it-up.svg'
}
Worker error:  Error [RuntimeError]: abort(Error: ENOENT: no such file or directory, open '[FILEPATH]\great-moves-keep-it-up.svg'). Build with -s ASSERTIONS=1 for more info.
    at process.w ([REDACTED]\AppData\Roaming\npm\node_modules\@squoosh\cli\build\index.js:7:376640)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Version:**
 - OS w/ version: Windows 10
 - Node version: 14.3.0
 - npm version: 6.14.6

**Comment by fernap3** [comment]
I just tested with one valid input file, and one nonexistent input file.  This case also crashes the app (I think `dispatchJob` is probably throwing). I think in this case I would expect the tool to print out a list of invalid filenames on startup, then decode/encode what it can.

**Comment by fernap3** [comment]
I have a fix for this in a local branch; happy to open a PR if I can get access.

![image](https://user-images.githubusercontent.com/1057057/101692995-023f8500-3a3f-11eb-8114-820352665031.png)
