### ISSUE TITLE
RuntimeError: abort(SyntaxError: JSON5: invalid character 'w' at 1:1)

### ISSUE THREAD

**Issue by steren** [GoogleChromeLabs/squoosh#956]
I ran `$ npx @squoosh/cli --webp wordpress-lighthouse.png wordpress-sources.png lighthouse-score-improve.png `

I got:

```
RuntimeError: abort(SyntaxError: JSON5: invalid character 'w' at 1:1). Build with -s ASSERTIONS=1 for more info.
    at process.w (/home/codespace/.npm/_npx/1912/lib/node_modules/@squoosh/cli/build/index.js:7:376640)
    at process.emit (events.js:315:20)
    at processEmit [as emit] (/home/codespace/.npm/_npx/1912/lib/node_modules/@squoosh/cli/build/index.js:7:79620)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by surma** [comment]
`--webp` takes a JSON parameter to configure the encoder, that’s why it’s trying to decode the first file name using JSON5. If you use `--webp '{}'`, it should work.

For now I’d recommend using the [web app](https://squoosh.app) to generate the CLI invocation, until we get around to extend the documentation (as outlined in #900). Closing this in favor of #900
