### ISSUE TITLE
CLI globalThis is not defined

### ISSUE THREAD

**Issue by rgarrigue** [GoogleChromeLabs/squoosh#982]
**Describe the bug**

Followed the cli/README.md, got an error stack straight away running `squoosh-cli` & `npx ...`. Couldn't find any further instruction live "use this node version" to fix it. 

**To Reproduce**

1. Install node 11.15.0 through NVM
2. `npm i -g squoosh-cli`
3. `squoosh-cli -h`

**Expected behavior**

Something else than an error stack !

**Version:**
 - OS w/ version: Ubuntu 20.04
 - Browser w/ version: not relevant
 - Node version: 11.15.0
 - npm version: 6.7.0 and 7.7.5 (tried before & after updating it)

**Additional context, screenshots, screencasts**

```
/home/remy/.nvm/versions/node/v11.15.0/lib/node_modules/@squoosh/cli/build/index.js:7
 - if the default executable name is not suitable, use the executableFile option to supply a custom name`;throw new Error(executableMissing)}else if(err.code==="EACCES"){throw new Error(`'${bin}' not executable`)}if(!exitCallback){process.exit(1)}else{const wrappedError=new CommanderError(1,"commander.executeSubCommandAsync","(error)");wrappedError.nestedError=err;exitCallback(wrappedError)}});this.runningCommand=proc}_dispatchSubcommand(commandName,operands,unknown){const subCommand=this._findCommand(commandName);if(!subCommand)this._helpAndError();if(subCommand._executableHandler){this._executeSubCommand(subCommand,operands.concat(unknown))}else{subCommand._parseCommand(operands,unknown)}}_parseCommand(operands,unknown){const parsed=this.parseOptions(unknown);operands=operands.concat(parsed.operands);unknown=parsed.unknown;this.args=operands.concat(unknown);if(operands&&this._findCommand(operands[0])){this._dispatchSubco

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/remy/.nvm/versions/node/v11.15.0/lib/node_modules/@squoosh/cli/build/index.js:7:375948)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by rgarrigue** [comment]
Tried other Node versions. Worked with Node 15. I wish there was a word about it in the CLI's README.md

**Comment by surma** [comment]
`globalThis` has been supported since Node 12. Node 11 is not a LTS release. Node 10 is a LTS release, but reaches end-of-life in 1 month(!). Most recent stable is Node 15. I think it’s reasonable to expect that our users have at least v12.
