### ISSUE TITLE
npm run build ERROR

### ISSUE THREAD

**Issue by lx1054331851** [GoogleChromeLabs/squoosh#992]
```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle squoosh@2.0.0~prebuild: squoosh@2.0.0
6 info lifecycle squoosh@2.0.0~build: squoosh@2.0.0
7 verbose lifecycle squoosh@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle squoosh@2.0.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lee/桌面/squoosh-dev/node_modules/.bin:/home/lee/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/lee/程序/pycharm-2021.1/bin
9 verbose lifecycle squoosh@2.0.0~build: CWD: /home/lee/桌面/squoosh-dev
10 silly lifecycle squoosh@2.0.0~build: Args: [ '-c', 'rollup -c && node lib/move-output.js' ]
11 silly lifecycle squoosh@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle squoosh@2.0.0~build: Failed to exec build script
13 verbose stack Error: squoosh@2.0.0 build: `rollup -c && node lib/move-output.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid squoosh@2.0.0
15 verbose cwd /home/lee/桌面/squoosh-dev
16 verbose Linux 5.8.0-49-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error squoosh@2.0.0 build: `rollup -c && node lib/move-output.js`
22 error Exit status 1
23 error Failed at the squoosh@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

ubuntu20.04 run squoosh error.

**Comment by surma** [comment]
Yeah, we don’t support Node 10 ([Node 10 reaches end of life in 5 days!](https://nodejs.org/en/about/releases/)) . Please manually update to _at least_ LTS (Node 14+) or use `nvm`, as we have a [`.nvmrc`](/GoogleChromeLabs/squoosh/blob/dev/.nvmrc) committed to the repo.
