### ISSUE TITLE
The mobile app is throwing error with AVIF codec.

### ISSUE THREAD

**Issue by arthurgubaidullin** [GoogleChromeLabs/squoosh#996]
**Describe the bug**
Installed application throws error "Processing error: RuntimeError: memory access out of bounds" on my Nokia 7 plus after selecting an image and changing the codec to AVIF. Sometimes this does not affect image processing and result.

**To Reproduce**
1. Go to 'start app screen'
2. Click on 'add image'
3. Select image
4. Change codec to 'AVIF'

**Expected behavior**
No error.

**Version:**
 - OS w/ version: Android 10 Build 00WW_4_15D_SP10
 - Browser w/ version: Chrome 90.0.4430.91

**Comment by jakearchibald** [comment]
Is this happening with all of the demo images, or only some?

**Comment by surma** [comment]
Yeah I can’t reproduce this on my phone with any of the example images or my own images. Can you provide a picture that causes this error for you?

**Comment by jakearchibald** [comment]
I think this is a follow-up from Twitter https://twitter.com/maybeArthurG/status/1387758504686018563.

In the screenshot the origin al 7mb which makes me think it's biiiig, so likely a genuine out of memory issue. Nokia 7 has either 4/6gb ram.

**Comment by arthurgubaidullin** [comment]
> Is this happening with all of the demo images, or only some?

No, but with demo image it throws another error.

![Screenshot_20210429-195557](https://user-images.githubusercontent.com/522932/116572355-56cb9a00-a925-11eb-9e14-f282fd2ac7ef.png)

> Yeah I can’t reproduce this on my phone with any of the example images or my own images. Can you provide a picture that causes this error for you?

Any images cause an error.

> I think this is a follow-up from Twitter https://twitter.com/maybeArthurG/status/1387758504686018563.

Yes.

> In the screenshot the origin al 7mb which makes me think it's biiiig, so likely a genuine out of memory issue. Nokia 7 has either 4/6gb ram.

Another error appears on the small file. :)

![Screenshot_20210429-195332](https://user-images.githubusercontent.com/522932/116572339-529f7c80-a925-11eb-9261-c6465c29c67b.png)

**Comment by jakearchibald** [comment]
> > Is this happening with all of the demo images, or only some?
> 
> No, but with demo image it throws another error.

Are you saying that every demo image fails to encode, although the error differs?

Do you also get an error with this image:

![638283338](https://user-images.githubusercontent.com/93594/116575663-c3836c00-a906-11eb-8b04-5e22e229f57e.png)

**Comment by arthurgubaidullin** [comment]
I tried to reproduce it on second phone, also a Nokia 7 Plus, I succeeded - I also get an error: "abort(undefined)".

Also on the demo image I got another error message.
![Screenshot (29 апр  2021 г  20_14_03)](https://user-images.githubusercontent.com/522932/116575805-6dbfbb80-a928-11eb-85e0-2f002973d6f9.jpg)

**Comment by arthurgubaidullin** [comment]
> > > Is this happening with all of the demo images, or only some?
> > 
> > 
> > No, but with demo image it throws another error.
> 
> Are you saying that every demo image fails to encode, although the error differs?
> 
> Do you also get an error with this image:
> 
> ![638283338](https://user-images.githubusercontent.com/93594/116575663-c3836c00-a906-11eb-8b04-5e22e229f57e.png)

Yes, I am getting different error messages.

Once there was no error with this image, the second time there was an error: "Encoding error".

**Comment by jyasskin** [comment]
With the Mario image on a laptop with 8G ram, on Edge 120.0.2210.91 (Official build) (64-bit), the Mario image fails to convert to AVIF with:

```
avif_enc_mt.worker-35de7c80.js:1  worker.js onmessage() captured an uncaught exception: RuntimeError: memory access out of bounds
r @ avif_enc_mt.worker-35de7c80.js:1
self.onmessage @ avif_enc_mt.worker-35de7c80.js:1
avif_enc_mt.worker-35de7c80.js:1  RuntimeError: memory access out of bounds
    at avif_enc_mt-d4922d65.wasm:0x0
    at Object.threadInit (avif_enc_mt-c20327c8.js:1:7791)
    at self.onmessage (avif_enc_mt.worker-35de7c80.js:1:1844)
```

The red panda example does work on Edge, as does Mario on Chrome on the same laptop.
